In [36]:
import pandas as pd
df= pd.read_csv("pandas_sales_project.csv")
df.head()

   Order_ID Customer_Name Region Product  Quantity  Price  Order_Date
0       101           Ali  North  Laptop         1  80000  2024-01-05
1       102          Sara  South  Mobile         2  40000  2024-01-06
2       103         Ahmed   East  Tablet         1  30000  2024-01-07
3       104        Ayesha   West  Laptop         3  80000  2024-01-08
4       105         Usman  North  Mobile         2  40000  2024-01-09

In [50]:
df.info

<bound method DataFrame.info of    Order_ID Customer_Name Region Product  Quantity  Price Order_Date  \
0       101           Ali  North  Laptop         1  80000 2024-01-05
1       102          Sara  South  Mobile         2  40000 2024-01-06
2       103         Ahmed   East  Tablet         1  30000 2024-01-07
3       104        Ayesha   West  Laptop         3  80000 2024-01-08
4       105         Usman  North  Mobile         2  40000 2024-01-09
5       106          Hina   East  Tablet         1  30000 2024-01-10
6       107         Bilal  South  Laptop         1  80000 2024-01-11
7       108          Noor   West  Mobile         4  40000 2024-01-12
8       109         Hamza  North  Tablet         2  30000 2024-01-13
9       110          Zara   East  Laptop         1  80000 2024-01-14

   Total_Sales
0        80000
1        80000
2        30000
3       240000
4        80000
5        30000
6        80000
7       160000
8        60000
9        80000  >

In [47]:
df["Total_Sales"] = df["Quantity"] * df["Price"]

In [39]:
df["Total_Sales"].sum()

np.int64(920000)

In [40]:
df.groupby("Product")["Total_Sales"].sum()

Product
Laptop    480000
Mobile    320000
Tablet    120000
Name: Total_Sales, dtype: int64

In [41]:
df.groupby("Region")["Total_Sales"].sum()

Region
East     140000
North    220000
South    160000
West     400000
Name: Total_Sales, dtype: int64

In [42]:
df.sort_values(by="Total_Sales", ascending=False)

,Order_ID,Customer_Name,Region,Product,Quantity,Price,Order_Date,Total_Sales
3,104,Ayesha,West,Laptop,3,80000,2024-01-08,240000
7,108,Noor,West,Mobile,4,40000,2024-01-12,160000
1,102,Sara,South,Mobile,2,40000,2024-01-06,80000
0,101,Ali,North,Laptop,1,80000,2024-01-05,80000
6,107,Bilal,South,Laptop,1,80000,2024-01-11,80000
4,105,Usman,North,Mobile,2,40000,2024-01-09,80000
9,110,Zara,East,Laptop,1,80000,2024-01-14,80000
8,109,Hamza,North,Tablet,2,30000,2024-01-13,60000
5,106,Hina,East,Tablet,1,30000,2024-01-10,30000
2,103,Ahmed,East,Tablet,1,30000,2024-01-07,30000

In [43]:
df[df["Quantity"] > 2]

,Order_ID,Customer_Name,Region,Product,Quantity,Price,Order_Date,Total_Sales
3,104,Ayesha,West,Laptop,3,80000,2024-01-08,240000
7,108,Noor,West,Mobile,4,40000,2024-01-12,160000

In [44]:
df["Product"].value_counts()

Product
Laptop    4
Mobile    3
Tablet    3
Name: count, dtype: int64

In [45]:
df.describe()

        Order_ID   Quantity         Price    Total_Sales
count   10.00000  10.000000     10.000000      10.000000
mean   105.50000   1.800000  53000.000000   92000.000000
std      3.02765   1.032796  23593.784492   63210.407019
min    101.00000   1.000000  30000.000000   30000.000000
25%    103.25000   1.000000  32500.000000   65000.000000
50%    105.50000   1.500000  40000.000000   80000.000000
75%    107.75000   2.000000  80000.000000   80000.000000
max    110.00000   4.000000  80000.000000  240000.000000

In [52]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [51]:
df["Month"] = df["Order_Date"].dt.month
df

,Order_ID,Customer_Name,Region,Product,Quantity,Price,Order_Date,Total_Sales,Month
0,101,Ali,North,Laptop,1,80000,2024-01-05,80000,1
1,102,Sara,South,Mobile,2,40000,2024-01-06,80000,1
2,103,Ahmed,East,Tablet,1,30000,2024-01-07,30000,1
3,104,Ayesha,West,Laptop,3,80000,2024-01-08,240000,1
4,105,Usman,North,Mobile,2,40000,2024-01-09,80000,1
5,106,Hina,East,Tablet,1,30000,2024-01-10,30000,1
6,107,Bilal,South,Laptop,1,80000,2024-01-11,80000,1
7,108,Noor,West,Mobile,4,40000,2024-01-12,160000,1
8,109,Hamza,North,Tablet,2,30000,2024-01-13,60000,1
9,110,Zara,East,Laptop,1,80000,2024-01-14,80000,1

In [53]:
df.to_csv("final_sales_analysis.csv", index=False)